### PR TITLE
add axes fixture to avoid random flip around x,y axis

### PR DESCRIPTION
**Pull request by taichiH**
I added pose fixture and the resulting captured image is here.
As you can see, all axes are fixed to same direction.

**without pose fixture**
before

**with pose fixture**
after

### CODE REVIEW

**Comment by iory** [comment]
Could you show me the results with the same scene?

**Comment by iory** [comment]
Video is better

**Comment by taichiH** [comment]
Adding videos.

with pose fixture
https://drive.google.com/file/d/1eioaDUCX9LhdHGFYGxrqt1RO6ySxhZUN/view?usp=sharing

without pose fixture
https://drive.google.com/file/d/1Z8zN1jPTPf93tx-DXPTCYy6BnDQHzBVf/view?usp=sharing

**Comment by iory** [comment]
Why z-axis is flipped?

**Pull request closed without merging**
